import type {
  CardDefinition,
  PhaseId,
  PhaseTone,
  PlayerRoleInPhase,
} from "@/lib/game/types";

export const PHASE_META: Record<
  PhaseId,
  {
    label: string;
    tone: PhaseTone;
  }
> = {
  opening: { label: "개막", tone: "system" },
  closeNeutral: { label: "근거리 교전", tone: "neutral" },
  midNeutral: { label: "중거리 교전", tone: "neutral" },
  farNeutral: { label: "원거리 교전", tone: "neutral" },
  pressure: { label: "압박 상황", tone: "advantage" },
  guard: { label: "가드 상황", tone: "neutral" },
  hardDown: { label: "하드 다운", tone: "danger" },
  combo: { label: "콤보 상황", tone: "advantage" },
};

export const UNIVERSAL_BURST_CARD: CardDefinition = {
  id: "universal_burst",
  phase: "universal",
  role: "universal",
  order: "B",
  title: "버스트",
  description:
    "한 게임에 한 번, 카드 배틀 결과를 무효화하고 상황을 리셋한다. 사이거리를 크게 벌린다.",
  tags: ["버스트", "무적"],
  color: "blue",
  groupLabel: "특수",
  baseWeight: 2,
  attackPower: 0,
  grabDamage: 0,
  advance: 0,
  push: 3,
  successOutcome: "neutralByDistance",
};

const OPENING_NEUTRAL: CardDefinition[] = [
  {
    id: "neutral_approach_opening",
    phase: "opening",
    role: "neutral",
    order: "01",
    title: "접근",
    description: "앞으로 압박하며 거리를 줄인다. 읽히면 위험하지만 흐름을 만들기 쉽다.",
    tags: ["뉴트럴", "대쉬", "지상", "딜레이"],
    color: "red",
    groupLabel: "개막",
    baseWeight: 12,
    attackPower: 0,
    grabDamage: 0,
    advance: 2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "neutral_poke_opening",
    phase: "opening",
    role: "neutral",
    order: "02",
    title: "견제",
    description: "중거리 기본기로 상대 접근을 끊는다. 개막에서 가장 안정적인 선택이다.",
    tags: ["뉴트럴", "지상", "중거리 공격"],
    color: "orange",
    groupLabel: "개막",
    baseWeight: 15,
    attackPower: 12,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "neutral_block_opening",
    phase: "opening",
    role: "neutral",
    order: "03",
    title: "방어",
    description: "리스크를 줄이며 상대의 강한 시도를 막는다. 큰 보상은 적지만 안정적이다.",
    tags: ["뉴트럴", "수비", "지상"],
    color: "blue",
    groupLabel: "개막",
    baseWeight: 13,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "neutral_evade_opening",
    phase: "opening",
    role: "neutral",
    order: "04",
    title: "회피",
    description: "뒤로 물러나거나 공중으로 빠지며 거리를 재조정한다.",
    tags: ["뉴트럴", "공중", "거리조절"],
    color: "gray",
    groupLabel: "개막",
    baseWeight: 10,
    attackPower: 0,
    grabDamage: 0,
    advance: -2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
];

const CLOSE_NEUTRAL: CardDefinition[] = [
  {
    id: "close_scrap",
    phase: "closeNeutral",
    role: "neutral",
    order: "01",
    title: "근접 승부",
    description: "근거리 기본기로 우선권 싸움을 건다. 영거리에서 가장 직관적인 선택지다.",
    tags: ["뉴트럴", "지상", "근거리 공격"],
    color: "red",
    groupLabel: "교전",
    baseWeight: 16,
    attackPower: 14,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "close_poke",
    phase: "closeNeutral",
    role: "neutral",
    order: "02",
    title: "견제",
    description: "한 박자 길게 내밀어 앞 움직임을 억제한다. 가까워도 여전히 유효하다.",
    tags: ["뉴트럴", "지상", "중거리 공격"],
    color: "orange",
    groupLabel: "교전",
    baseWeight: 11,
    attackPower: 12,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "close_throw",
    phase: "closeNeutral",
    role: "neutral",
    order: "03",
    title: "영거리 잡기",
    description: "최종 거리 0의 초근접 특수 선택지. 공격 포함 태그와 수비를 대부분 먼저 잡아낸다.",
    tags: ["선공", "지상", "잡기"],
    color: "gold",
    groupLabel: "교전",
    baseWeight: 9,
    attackPower: 0,
    grabDamage: 16,
    advance: 0,
    push: 0,
    successOutcome: "hardDown",
  },
  {
    id: "close_block",
    phase: "closeNeutral",
    role: "neutral",
    order: "04",
    title: "방어",
    description: "상대의 근거리 시도를 안전하게 받아낸다. 성공 시 흐름을 잠시 끊는다.",
    tags: ["뉴트럴", "수비", "지상"],
    color: "blue",
    groupLabel: "교전",
    baseWeight: 13,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "close_escape",
    phase: "closeNeutral",
    role: "neutral",
    order: "05",
    title: "회피",
    description: "백대쉬, 백점프, 앞점프 등으로 압박각을 흐린다.",
    tags: ["뉴트럴", "공중", "거리조절"],
    color: "gray",
    groupLabel: "교전",
    baseWeight: 9,
    attackPower: 0,
    grabDamage: 0,
    advance: -2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "close_reversal",
    phase: "closeNeutral",
    role: "neutral",
    order: "06",
    title: "승부수",
    description: "무적기를 지른다. 성공하면 흐름을 강제로 리셋하지만, 실패 리스크도 크다.",
    tags: ["무적", "지상", "근거리 공격", "캔슬불가"],
    color: "gray",
    groupLabel: "교전",
    baseWeight: 5,
    attackPower: 18,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
];

const MID_NEUTRAL: CardDefinition[] = [
  {
    id: "mid_approach",
    phase: "midNeutral",
    role: "neutral",
    order: "01",
    title: "접근",
    description: "대쉬, 전진 점프로 중거리 싸움을 근거리로 끌어당긴다.",
    tags: ["뉴트럴", "대쉬", "지상", "딜레이"],
    color: "red",
    groupLabel: "교전",
    baseWeight: 13,
    attackPower: 0,
    grabDamage: 0,
    advance: 2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "mid_poke",
    phase: "midNeutral",
    role: "neutral",
    order: "02",
    title: "견제",
    description: "중거리에서 가장 표준적인 버튼. 상대 전진과 무리한 이동을 자주 끊는다.",
    tags: ["뉴트럴", "지상", "중거리 공격"],
    color: "orange",
    groupLabel: "교전",
    baseWeight: 16,
    attackPower: 12,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "mid_long",
    phase: "midNeutral",
    role: "neutral",
    order: "03",
    title: "장거리 견제",
    description: "더 먼 거리까지 닿는 길쭉한 선택지다. 리턴은 낮지만 범위가 넓다.",
    tags: ["뉴트럴", "지상", "원거리 공격"],
    color: "gold",
    groupLabel: "교전",
    baseWeight: 12,
    attackPower: 10,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "mid_block",
    phase: "midNeutral",
    role: "neutral",
    order: "04",
    title: "방어",
    description: "상대의 긴 견제나 승부수를 먼저 확인한다.",
    tags: ["뉴트럴", "수비", "지상"],
    color: "blue",
    groupLabel: "교전",
    baseWeight: 11,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "mid_escape",
    phase: "midNeutral",
    role: "neutral",
    order: "05",
    title: "회피",
    description: "공중 이동과 거리조절로 중거리 탐색을 다시 시작한다.",
    tags: ["뉴트럴", "공중", "거리조절"],
    color: "gray",
    groupLabel: "교전",
    baseWeight: 8,
    attackPower: 0,
    grabDamage: 0,
    advance: -2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
];

const FAR_NEUTRAL: CardDefinition[] = [
  {
    id: "far_approach",
    phase: "farNeutral",
    role: "neutral",
    order: "01",
    title: "접근",
    description: "원거리에서 가장 중요한 카드. 대쉬와 점프로 거리를 급격히 좁힌다.",
    tags: ["뉴트럴", "대쉬", "지상", "딜레이"],
    color: "red",
    groupLabel: "교전",
    baseWeight: 15,
    attackPower: 0,
    grabDamage: 0,
    advance: 2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "far_long",
    phase: "farNeutral",
    role: "neutral",
    order: "02",
    title: "장거리 견제",
    description: "멀리서 상대 접근을 끊는다. 리턴보다 라인 관리가 목적이다.",
    tags: ["뉴트럴", "지상", "원거리 공격"],
    color: "orange",
    groupLabel: "교전",
    baseWeight: 17,
    attackPower: 11,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "far_block",
    phase: "farNeutral",
    role: "neutral",
    order: "03",
    title: "방어",
    description: "상대 장거리 견제와 승부수를 먼저 확인한다.",
    tags: ["뉴트럴", "수비", "지상"],
    color: "blue",
    groupLabel: "교전",
    baseWeight: 10,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "far_escape",
    phase: "farNeutral",
    role: "neutral",
    order: "04",
    title: "회피",
    description: "거리를 더 벌리거나 공중 타이밍을 섞어 상대 리듬을 흔든다.",
    tags: ["뉴트럴", "공중", "거리조절"],
    color: "gray",
    groupLabel: "교전",
    baseWeight: 8,
    attackPower: 0,
    grabDamage: 0,
    advance: -2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
];

const PRESSURE_ATTACKER: CardDefinition[] = [
  {
    id: "pressure_string",
    phase: "pressure",
    role: "attacker",
    order: "01",
    title: "연속 압박",
    description: "기본기와 연속 개틀링으로 상대를 계속 묶는다. 가장 표준적인 유지 선택지다.",
    tags: ["지상", "근거리 공격"],
    color: "red",
    groupLabel: "공격자",
    baseWeight: 15,
    attackPower: 11,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "pressure_frame",
    phase: "pressure",
    role: "attacker",
    order: "02",
    title: "프레임 트랩",
    description: "딜레이를 섞어 반항을 노리는 카드다. 맞으면 큰 리턴으로 이어진다.",
    tags: ["지상", "딜레이", "근거리 공격", "콤보"],
    color: "orange",
    groupLabel: "공격자",
    baseWeight: 13,
    attackPower: 18,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "combo",
  },
  {
    id: "pressure_throw",
    phase: "pressure",
    role: "attacker",
    order: "03",
    title: "잡기",
    description: "수비 굳히기를 깨는 영거리 잡기다. 최종 거리 0에서만 진짜 위협이 된다.",
    tags: ["선공", "지상", "잡기"],
    color: "gold",
    groupLabel: "공격자",
    baseWeight: 10,
    attackPower: 0,
    grabDamage: 16,
    advance: 0,
    push: 0,
    successOutcome: "hardDown",
  },
  {
    id: "pressure_mix",
    phase: "pressure",
    role: "attacker",
    order: "04",
    title: "이지선다",
    description: "중단/하단/딜레이를 섞어 수비 타이밍을 흔든다.",
    tags: ["지상", "이지선다", "하단", "근거리 공격"],
    color: "gold",
    groupLabel: "공격자",
    baseWeight: 12,
    attackPower: 14,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
];

const PRESSURE_DEFENDER: CardDefinition[] = [
  {
    id: "defend_guard",
    phase: "pressure",
    role: "defender",
    order: "01",
    title: "가드",
    description: "가장 안정적인 선택. 성공하면 상대를 밀어내며 흐름을 잠시 끊는다.",
    tags: ["수비", "지상"],
    color: "blue",
    groupLabel: "수비자",
    baseWeight: 17,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "defend_abare",
    phase: "pressure",
    role: "defender",
    order: "02",
    title: "반항",
    description: "틈을 보고 버튼을 누른다. 맞으면 흐름을 되찾지만 프레임 트랩엔 크게 당한다.",
    tags: ["지상", "딜레이", "근거리 공격"],
    color: "red",
    groupLabel: "수비자",
    baseWeight: 8,
    attackPower: 12,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "defend_escape",
    phase: "pressure",
    role: "defender",
    order: "03",
    title: "탈출",
    description: "백대쉬, 점프, 공중 이동으로 압박을 비튼다.",
    tags: ["공중", "거리조절"],
    color: "gray",
    groupLabel: "수비자",
    baseWeight: 11,
    attackPower: 0,
    grabDamage: 0,
    advance: -2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "defend_throw",
    phase: "pressure",
    role: "defender",
    order: "04",
    title: "잡기",
    description: "근거리 압박에서만 통하는 특수 반응. 최종 거리 0에서 성립한다.",
    tags: ["선공", "지상", "잡기"],
    color: "gold",
    groupLabel: "수비자",
    baseWeight: 7,
    attackPower: 0,
    grabDamage: 14,
    advance: 0,
    push: 0,
    successOutcome: "hardDown",
  },
  {
    id: "defend_reversal",
    phase: "pressure",
    role: "defender",
    order: "05",
    title: "승부수",
    description: "무적기로 압박을 뒤집는다. 가장 강하지만 가장 위험하다.",
    tags: ["무적", "지상", "근거리 공격", "캔슬불가"],
    color: "gray",
    groupLabel: "수비자",
    baseWeight: 5,
    attackPower: 20,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
];

const HARDDOWN_ATTACKER: CardDefinition[] = [
  {
    id: "okizeme_meaty",
    phase: "hardDown",
    role: "attacker",
    order: "01",
    title: "깔아두기",
    description: "상대 기상 타이밍에 맞춰 압박을 미리 깔아둔다.",
    tags: ["지상", "근거리 공격"],
    color: "red",
    groupLabel: "공격자",
    baseWeight: 15,
    attackPower: 12,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
  {
    id: "okizeme_wait",
    phase: "hardDown",
    role: "attacker",
    order: "02",
    title: "지켜보기",
    description: "무적기와 버스트를 의식하며 한 템포 늦춘다.",
    tags: ["수비", "지상"],
    color: "blue",
    groupLabel: "공격자",
    baseWeight: 10,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "okizeme_loop",
    phase: "hardDown",
    role: "attacker",
    order: "03",
    title: "재차 압박",
    description: "기상 직후 다시 한번 읽기 싸움을 강요한다.",
    tags: ["지상", "이지선다", "근거리 공격"],
    color: "orange",
    groupLabel: "공격자",
    baseWeight: 12,
    attackPower: 15,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
];

const HARDDOWN_DEFENDER: CardDefinition[] = [
  {
    id: "wake_guard",
    phase: "hardDown",
    role: "defender",
    order: "01",
    title: "안전기상",
    description: "기상 가드로 가장 안정적으로 버틴다.",
    tags: ["수비", "지상"],
    color: "blue",
    groupLabel: "수비자",
    baseWeight: 16,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
  {
    id: "wake_escape",
    phase: "hardDown",
    role: "defender",
    order: "02",
    title: "탈출기상",
    description: "점프나 백대쉬 계열로 위험한 기상 압박을 피한다.",
    tags: ["공중", "거리조절"],
    color: "gray",
    groupLabel: "수비자",
    baseWeight: 10,
    attackPower: 0,
    grabDamage: 0,
    advance: -2,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "wake_reversal",
    phase: "hardDown",
    role: "defender",
    order: "03",
    title: "반전기상",
    description: "무적기 기상으로 흐름을 강제로 뒤집는다.",
    tags: ["무적", "지상", "근거리 공격", "캔슬불가"],
    color: "gray",
    groupLabel: "수비자",
    baseWeight: 6,
    attackPower: 20,
    grabDamage: 0,
    advance: 0,
    push: 1,
    successOutcome: "neutralByDistance",
  },
];

const COMBO_ATTACKER: CardDefinition[] = [
  {
    id: "combo_max",
    phase: "combo",
    role: "attacker",
    order: "01",
    title: "최대 데미지",
    description: "당장 가장 큰 피해를 우선한다. 세 번쯤 맞으면 라운드가 끝날 수준의 화력이다.",
    tags: ["지상", "근거리 공격", "콤보"],
    color: "red",
    groupLabel: "공격자",
    baseWeight: 15,
    attackPower: 34,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "neutralByDistance",
  },
  {
    id: "combo_down",
    phase: "combo",
    role: "attacker",
    order: "02",
    title: "다운 마무리",
    description: "화력은 조금 줄이는 대신 하드 다운과 기상 심리로 이어간다.",
    tags: ["지상", "근거리 공격", "다운"],
    color: "orange",
    groupLabel: "공격자",
    baseWeight: 12,
    attackPower: 28,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "hardDown",
  },
  {
    id: "combo_reset",
    phase: "combo",
    role: "attacker",
    order: "03",
    title: "압박 리셋",
    description: "데미지는 줄지만 곧바로 압박 상황으로 복귀한다.",
    tags: ["지상", "근거리 공격", "딜레이"],
    color: "gold",
    groupLabel: "공격자",
    baseWeight: 9,
    attackPower: 18,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "pressure",
  },
];

const COMBO_DEFENDER: CardDefinition[] = [
  {
    id: "combo_hold",
    phase: "combo",
    role: "defender",
    order: "01",
    title: "버티기",
    description: "자원을 아끼고 피해를 감수한다. 별도 반전은 없다.",
    tags: ["수비"],
    color: "blue",
    groupLabel: "수비자",
    baseWeight: 14,
    attackPower: 0,
    grabDamage: 0,
    advance: 0,
    push: 0,
    successOutcome: "samePhase",
  },
];

export function getCardsForPhase(
  phase: PhaseId,
  role: PlayerRoleInPhase
): CardDefinition[] {
  if (phase === "opening") return OPENING_NEUTRAL;
  if (phase === "closeNeutral") return CLOSE_NEUTRAL;
  if (phase === "midNeutral") return MID_NEUTRAL;
  if (phase === "farNeutral") return FAR_NEUTRAL;
  if (phase === "pressure") return role === "attacker" ? PRESSURE_ATTACKER : PRESSURE_DEFENDER;
  if (phase === "guard") return role === "attacker" ? PRESSURE_ATTACKER : PRESSURE_DEFENDER;
  if (phase === "hardDown") return role === "attacker" ? HARDDOWN_ATTACKER : HARDDOWN_DEFENDER;
  if (phase === "combo") return role === "attacker" ? COMBO_ATTACKER : COMBO_DEFENDER;
  return OPENING_NEUTRAL;
}